#!/usr/bin/env python3
"""Generate the C++ data tables from data/*.json.

Emits static, constexpr-friendly arrays so the core needs no JSON parser and no
data files at runtime -- important for the plugin, which cannot rely on paths.
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "motif-xs-core" / "src"

SCOPE_ENUM = {
    "system": "System", "mode_change": "ModeChange",
    "part_set_control": "PartSetControl", "bulk_control": "BulkControl",
    "normal_voice_common": "NormalVoiceCommon",
    "normal_voice_element": "NormalVoiceElement",
    "drum_voice_common": "DrumVoiceCommon", "drum_voice_key": "DrumVoiceKey",
    "multi_common": "MultiCommon", "multi_part": "MultiPart",
}
ENC = {"direct": "Direct", "msb_lsb": "MsbLsb", "nibbles": "Nibbles"}


def cstr(s):
    if s is None:
        s = ""
    s = str(s).replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\n", " ").replace("\r", " ")
    # keep the generated source ASCII-clean
    # Yamaha's PDFs use typographic punctuation; fold it to ASCII rather than
    # letting the "?" fallback mangle names like "Dual Coil '65".
    for src, dst in (("\u2013", "-"), ("\u2014", "-"),
                     ("\u2018", "'"), ("\u2019", "'"),
                     ("\u201c", "'"), ("\u201d", "'"),
                     ("\u2192", "->"), ("\u00b0", "deg"),
                     ("\u00d7", "x"), ("\u2026", "..."),
                     ("\u221e", "inf")):
        s = s.replace(src, dst)
    return '"' + "".join(c if 32 <= ord(c) < 127 else "?" for c in s) + '"'


def addr_byte(v):
    """Hex byte literal, or 0 for a variable placeholder."""
    if re.fullmatch(r"[0-9A-F]{2}", v):
        return f"0x{v}"
    return "0x00"


def variable_of(a):
    hi, mid, low = a["high"], a["mid"], a["low"]
    if mid == "ee":
        return "Element"
    if mid == "pp":
        return "Part"
    if low == "nn" or mid == "nn":
        return "Program"
    if re.fullmatch(r"[0-9A-F]n", mid):
        return "Table"
    return "None"


def gen_parameters():
    d = json.loads((ROOT / "data" / "parameters.json").read_text())
    out = ["// Generated by tools/gen_tables.py -- do not edit.",
           '#include "motifxs/parameters.hpp"', "",
           "namespace motifxs {", "namespace {",
           "constexpr Parameter kParameters[] = {"]
    for p in d["parameters"]:
        a = p["address"]
        lo = p["min"] if p["min"] is not None else 0
        hi = p["max"] if p["max"] is not None else 0
        # 'Table' variables live in the low nibble of the Mid byte
        mid = a["mid"]
        midlit = addr_byte(mid) if re.fullmatch(r"[0-9A-F]{2}", mid) else (
            f"0x{mid[0]}0" if re.fullmatch(r"[0-9A-F]n", mid) else "0x00")
        out.append(
            "  {%s, %s, Scope::%s, %s, %s, %s, AddressVariable::%s, %d, Encoding::%s, %d, %d, %s, %s}," % (
                cstr(p["id"]), cstr(p["name"]), SCOPE_ENUM[p["scope"]],
                addr_byte(a["high"]), midlit, addr_byte(a["low"]),
                variable_of(a), p["size"], ENC[p["encoding"]],
                lo, hi, "true" if p["reserved"] else "false",
                cstr(p["description"])))
    out += ["};", "}  // namespace", "",
            "std::span<const Parameter> allParameters() { return kParameters; }",
            "}  // namespace motifxs", ""]
    (SRC / "parameter_table.cpp").write_text("\n".join(out))
    return len(d["parameters"])


def gen_catalog():
    v = json.loads((ROOT / "data" / "voices.json").read_text())
    a = json.loads((ROOT / "data" / "arpeggios.json").read_text())
    wf = json.loads((ROOT / "data" / "waveforms.json").read_text())
    out = ["// Generated by tools/gen_tables.py -- do not edit.",
           '#include "motifxs/catalog.hpp"', "",
           "namespace motifxs {", "namespace {",
           "constexpr Voice kVoices[] = {"]
    for x in v["voices"]:
        out.append("  {%s, %d, %d, %d, %s, %s, %s, %s, VoiceKind::%s}," % (
            cstr(x["bank"]), x["msb"], x["lsb"], x["program"],
            cstr(x["slot"] or ""), cstr(x["name"]),
            cstr(x["category_main"] or ""), cstr(x["category_sub"] or ""),
            "Drum" if x["type"] == "drum" else "Normal"))
    out += ["};", "", "constexpr Arpeggio kArpeggios[] = {"]
    for x in a["arpeggios"]:
        out.append("  {%d, %s, %s, %s, %s, %d, %d, %s, %s, %s}," % (
            x["number"], cstr(x["name"]), cstr(x["main_category"]),
            cstr(x["sub_category"]), cstr(x["time_signature"]),
            x["length"], x["original_tempo"],
            "true" if x["accent"] else "false",
            "true" if x["random_sfx"] else "false",
            cstr(x["voice_type"] or "")))
    out += ["};", "", "constexpr Waveform kWaveforms[] = {"]
    for x in wf["waveforms"]:
        out.append("  {%d, %s, %s}," % (x["number"], cstr(x["category"]), cstr(x["name"])))
    out += ["};", "}  // namespace", "",
            "std::span<const Voice> allVoices() { return kVoices; }",
            "std::span<const Arpeggio> allArpeggios() { return kArpeggios; }",
            "std::span<const Waveform> allWaveforms() { return kWaveforms; }",
            "}  // namespace motifxs", ""]
    (SRC / "catalog_table.cpp").write_text("\n".join(out))
    return len(v["voices"]), len(a["arpeggios"]), len(wf["waveforms"])


if __name__ == "__main__":
    SRC.mkdir(parents=True, exist_ok=True)
    n = gen_parameters()
    nv, na, nw = gen_catalog()
    print(f"generated parameter_table.cpp ({n} parameters)")
    print(f"generated catalog_table.cpp   ({nv} voices, {na} arpeggios, {nw} waveforms)")
